version: "3"

services:
  growbox_daemon:
    build: ./backend/book_daemon
    depends_on:
      - growbox_database
    expose:
      - 8080

  growbox_database:
    platform: linux/x86_64
    image: mysql:5.7
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - ./growbox_database:/docker-entrypoint-initdb.d/:ro
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
  